#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option docker)
ARCH_OPTION=$(arch_option)


if [ ! -d "${HOME}/.docker" ]; then
    mkdir -p "${HOME}/.docker"
fi
if [ ! -f "${HOME}/.actrc" ]; then
    touch "${HOME}/.actrc"
fi

DOCKER_IMAGE="tei1988/act:0.2.23-alpine"
docker run ${ARCH_OPTION} -it ${USER_OPTION} -w "/${PWD}" -v "${PWD}:/${PWD}" -v "${HOME}/.docker:/root/.docker:rw" -v "${HOME}/.actrc:/root/.actrc:rw" -v /var/run/docker.sock:/var/run/docker.sock --rm "${DOCKER_IMAGE}" "$@"
