#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
CMD=$(basename $0)
USER_OPTION=$(user_option)
ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

DOCKER_IMAGE_NAME="tei1988/coreutils"
DOCKER_IMAGE_TAG="9.4-r1"
DOCKER_IMAGE="${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"

docker run ${ARCH_OPTION}  -i ${TTY_OPTION} ${USER_OPTION} --entrypoint ${CMD} -w ${PWD} --rm "${DOCKER_IMAGE}" "$@"
