#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option docker)
ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

if [ ! -d "${HOME}/.config/gcloud" ]; then
    mkdir -p "${HOME}/.config/gcloud"
fi
if [ ! -d "${HOME}/.docker" ]; then
    mkdir -p "${HOME}/.docker"
fi
if [ ! -d "${HOME}/.kube" ]; then
    mkdir -p "${HOME}/.kube"
fi

DOCKER_IMAGE="google/cloud-sdk:415.0.0-slim"
docker run ${ARCH_OPTION} -i ${TTY_OPTION} ${USER_OPTION} --entrypoint gcloud -w "${PWD}" -v "${PWD}:${PWD}:rw" -v "${HOME}/.docker:/.docker:rw" -v "${HOME}/.kube:/.kube:rw" -v "${HOME}/.config/gcloud:/.config/gcloud:rw" --rm "${DOCKER_IMAGE}" "$@"
