#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)

if [ ! -d "${HOME}/.config/gcloud" ]; then
    mkdir -p "${HOME}/.config/gcloud"
fi
if [ ! -d "${HOME}/.docker" ]; then
    mkdir -p "${HOME}/.docker"
fi

DOCKER_IMAGE="tei1988/cloud-build-local:0.5.0-alpine"
docker run -it ${USER_OPTION} --entrypoint gcloud -v "${HOME}/.docker:/.docker:rw" -v "${HOME}/.config/gcloud:/.config/gcloud:rw" --rm "${DOCKER_IMAGE}" "$@"
