#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)

DOCKER_IMAGE="alpine/git:v2.26.2"
docker run -it ${USER_OPTION} -w /src -v "${PWD}:/src" -v "${HOME}/.gitconfig:/.gitconfig:rw" -v "${HOME}/.ssh:/.ssh:ro" --rm "${DOCKER_IMAGE}" "$@"
