#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
#USER_OPTION=$(user_option)
#ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

if [ ! -d "${HOME}/.cache/go-build" ]; then
    mkdir -p "${HOME}/.cache/go-build"
fi

GO_VERSION=${GO_VERSION:-$(cat .go-version)}
DOCKER_IMAGE="golang:${GO_VERSION}-bullseye"
GO111MODULE=${GO111MODULE:-on}
GOOS=${GOOS:-linux}
GOARCH=${GOARCH:-amd64}

docker run ${ARCH_OPTION} -i ${TTY_OPTION} ${USER_OPTION} -e GO111MODULE=${GO111MODULE} -e GOOS=${GOOS} -e GOARCH=${GOARCH} --entrypoint go -v "${HOME}/.cache/go-build:/root/.cache/go-build" -v "${PWD}:${PWD}" -w "${PWD}" --rm "${DOCKER_IMAGE}" "$@"
