#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)

if [ ! -d "${HOME}/.cache/go-build" ]; then
    mkdir -p "${HOME}/.cache/go-build"
fi

DOCKER_IMAGE="golang:1.14.4-buster"
docker run -it ${USER_OPTION} -e GO111MODULE=on --entrypoint go -v "${HOME}/.cache/go-build:/.cache/go-build" -v "${PWD}:/go" --rm "${DOCKER_IMAGE}" "$@"
