#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)
ARCH_OPTION=$(arch_option)

if [ ! -d "${HOME}/.cache/go-build" ]; then
    mkdir -p "${HOME}/.cache/go-build"
fi

GO_VERSION=${GO_VERSION:-$(cat .go-version)}
DOCKER_IMAGE="golang:${GO_VERSION}-buster"
GO111MODULE=${GO111MODULE:-on}

docker run ${ARCH_OPTION} -it ${USER_OPTION} -e GO111MODULE=${GO111MODULE} --entrypoint go -v "${HOME}/.cache/go-build:/.cache/go-build" -v "${PWD}:${PWD}" -w "${PWD}" --rm "${DOCKER_IMAGE}" "$@"
