#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)
ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

DOCKER_IMAGE="tei1988/jq:1.6-alpine"
docker run ${ARCH_OPTION} -i ${TTY_OPTION} ${USER_OPTION} --rm "${DOCKER_IMAGE}" "$@"
