#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)
ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

DOCKER_IMAGE="rancher/kubectl:v1.28.5"
PORT_OPTION=${PORT_OPTION:-}
VOLUME_OPTION="-v ${HOME}/.kube:/home/kubectl/.kube:ro"
docker run ${ARCH_OPTION} -i ${TTY_OPTION} ${USER_OPTION} ${VOLUME_OPTION} ${PORT_OPTION} --rm "${DOCKER_IMAGE}" "$@"
