#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
CMD=$(basename $0)
USER_OPTION=$(user_option)
#ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

if [ ! -f "${HOME}/.npmrc" ]; then
    touch "${HOME}/.npmrc"
fi
if [ ! -d "${HOME}/.npm" ]; then
    mkdir -p "${HOME}/.npm"
fi
if [ ! -d "${HOME}/.config/gcloud" ]; then
    mkdir -p "${HOME}/.config/gcloud"
fi

PORT_OPTION=${PORT_OPTION:-}
NODE_VERSION=${NODE_VERSION:-$(cat .node-version)}
DOCKER_IMAGE="tei1988/node:${NODE_VERSION#v}-alpine"
docker run ${PORT_OPTION} ${ARCH_OPTION} -e NODE_ENV -i ${TTY_OPTION} ${USER_OPTION} -v "${HOME}/.npmrc:/.npmrc:rw" -v "${HOME}/.npm:/.npm:rw" -v "${HOME}/.config/gcloud:/.config/gcloud:ro" --entrypoint ${CMD} -w "${PWD}" -v "${PWD}:${PWD}:rw" --rm "${DOCKER_IMAGE}" "$@"
