#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
CMD=$(basename $0)
USER_OPTION=$(user_option)
#ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

if [ ! -f "${HOME}/.npmrc" ]; then
    touch "${HOME}/.npmrc"
fi
if [ ! -d "${HOME}/.npm" ]; then
    mkdir -p "${HOME}/.npm"
fi
PORT_OPTION=${PORT_OPTION:-}
NODE_VERSION=${NODE_VERSION:-$(cat .node-version)}
DOCKER_IMAGE="tei1988/node:${NODE_VERSION}-alpine"
docker run ${ARCH_OPTION} -i ${TTY_OPTION} ${USER_OPTION} -v "${HOME}/.npmrc:/home/node/.npmrc:rw" -v "${HOME}/.npm:/home/node/.npm:rw" --entrypoint ${CMD} -w "${PWD}" -v "${PWD}:${PWD}:rw" --rm "${DOCKER_IMAGE}" "$@"
