#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
CMD=$(basename $0)
USER_OPTION=$(user_option)
ARCH_OPTION=$(arch_option)
TTY_OPTION=$(tty_option)

DOCKER_IMAGE_NAME="tei1988/pcre2-tools"
DOCKER_IMAGE_TAG="10.42-r2"
DOCKER_IMAGE="${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"

docker run ${ARCH_OPTION} -it ${USER_OPTION} --entrypoint ${CMD:-"pcre2grep"} -w /src -v "${PWD}:/src" --rm "${DOCKER_IMAGE}" "$@"
