#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)
ARCH_OPTION=$(arch_option)

DOCKER_IMAGE="tei1988/poppler-utils:0.88.0-alpine"
docker run ${ARCH_OPTION} -it ${USER_OPTION} --entrypoint pdfunite -w /src -v "${PWD}:/src" --rm "${DOCKER_IMAGE}" "$@"
