#!/bin/sh -e

TERRAFORM_BASE_DIR_AUTO=$(cat **.tf | pcre2grep -r -N ANYCRLF -M -e 'source *= *"((?=[^"]+)[./]+).*"' --only-matching=1 | uniq)
TERRAFORM_BASE_DIR=${TERRAFORM_BASE_DIR:-${TERRAFORM_BASE_DIR_AUTO}}
TERRAFORM_MOUNT_POINT=$(realpath "${TERRAFORM_BASE_DIR:-./}")
TERRAFORM_WORKDIR=$(realpath --relative-to=${TERRAFORM_MOUNT_POINT} ${PWD})

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option nobody)

if [ ! -d "${HOME}/.config/gcloud" ]; then
    mkdir -p "${HOME}/.config/gcloud"
fi
if [ ! -d "${HOME}/.aws" ]; then
    mkdir -p "${HOME}/.aws"
fi

TERRAFORM_VERSION=${TERRAFORM_VERSION:-$(cat .terraform-version)}
DOCKER_IMAGE=${DOCKER_IMAGE:-"hashicorp/terraform:${TERRAFORM_VERSION}"}
docker run -it ${USER_OPTION} -v "${HOME}/.cache/helm/repository/:/.cache/helm/repository/:rw" -w "/src/${TERRAFORM_WORKDIR}" -v "${TERRAFORM_MOUNT_POINT}:/src" -v "${HOME}/.config/gcloud:/.config/gcloud:ro" -v "${HOME}/.aws:/.aws:ro" -v "${HOME}/.kube:/.kube:ro" --rm "${DOCKER_IMAGE}" "$@"
