#!/bin/sh -e

. "$(dirname "$(readlink "$0")")/../libs/user_option.sh"
USER_OPTION=$(user_option)
ARCH_OPTION=$(arch_option)

DOCKER_IMAGE="kubeless/unzip:latest"
docker run ${ARCH_OPTION} ${USER_OPTION} --entrypoint unzip -w /src -v "${PWD}:/src" --rm "${DOCKER_IMAGE}" "$@"
